# Generated by Django 5.1.2 on 2025-01-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses1', to='roadmap2.stage'),
        ),
    ]
