# Generated by Django 5.1.2 on 2025-01-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='course',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_slide',
        ),
        migrations.RemoveField(
            model_name='test',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='stage',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
