# Generated by Django 5.1.2 on 2025-01-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_testattempt_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.roadmapslide'),
        ),
    ]
