# Generated by Django 5.1.2 on 2025-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_userprogress_current_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
