# Generated by Django 5.1.2 on 2025-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_userprogress_test_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='test_completed',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', to='roadmap.roadmapcourse'),
        ),
    ]
