# Generated by Django 5.1.2 on 2025-02-09 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_remove_userprogress_test_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_points', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmapcourse')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmapstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User XP',
                'verbose_name_plural': 'User XP',
                'ordering': ['-xp_points'],
                'unique_together': {('user', 'stage', 'course')},
            },
        ),
    ]
