# Generated by Django 5.1.2 on 2025-02-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_userxp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserXP',
        ),
    ]
