# Generated by Django 5.1.2 on 2025-02-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_userstagetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStageTime',
        ),
    ]
