# Generated by Django 5.1.2 on 2024-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(default='kjdfkjhsdkk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='bkj,xfbkjfkjsb', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='dxgfdhbdfhb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='fgvd.mblkjmdfb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default=65454423, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='xcbd g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(default='dfvrsgdfrb'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
