# Generated by Django 5.1.2 on 2025-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='solution',
            field=models.TextField(default='Def func():'),
        ),
    ]
