# Generated by Django 5.1.2 on 2025-01-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_codingquestion_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='solution',
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='function_name',
            field=models.CharField(default='aa', max_length=100),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='input_format',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('single_input', 'Single Input'), ('multiple_input', 'Multiple Input Lines'), ('array_target', 'Array with Target'), ('matrix_input', 'Matrix Input')], default='gg', max_length=50),
        ),
    ]
