# Generated by Django 5.1.2 on 2025-01-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_codingquestion_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='solution',
            field=models.CharField(default='func', max_length=500),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='function_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('array_target', 'Array with Target'), ('single_input', 'Single Input'), ('multiple_input', 'Multiple Input Lines'), ('matrix_input', 'Matrix Input')], default='array_target', max_length=50),
        ),
    ]
