# Generated by Django 5.1.2 on 2025-01-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_codingquestion_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='solution',
            field=models.TextField(default='func'),
        ),
    ]
