# Generated by Django 5.1.2 on 2025-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_codingquestion_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='solution',
            field=models.TextField(default='Def func():'),
        ),
    ]
