# Generated by Django 5.1.2 on 2025-02-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Name',
            field=models.CharField(default='Guid User', max_length=255),
        ),
    ]
