# Generated by Django 5.1.2 on 2025-02-22 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stage1_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage2_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage3_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage4_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage5_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage6_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage7_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stage8_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
