# Generated by Django 5.1.2 on 2025-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_stage1_score_customuser_stage2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
