# Generated by Django 5.1.2 on 2025-03-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification_send_to_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='send_to_all',
        ),
    ]
