# Generated by Django 5.1.2 on 2025-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_notification_send_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
